swagger: "2.0"
info:
  description: ""
  version: "0.1"
  title: "Servitiom"
  license:
    name: "MPL-2.0"
    url: "http://mozilla.org/MPL/2.0/"
host: "localhost"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /service/health:
    get:
      summary: "Return info about service health condition"
      operationId: "serviceHealth"
      responses:
        200:
          description: "Service healthy"
  /services:
    post:
      summary: "Create service"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Service entity data"
        required: true
        schema:
          $ref: "#/definitions/Service"
      responses:
        201:
          description: "Created sucessfully"
        405:
          description: "Invalid input"
    get:
      summary: "Creates service"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Service entity data"
        required: true
        schema:
          $ref: "#/definitions/Service"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Service"
        405:
          description: "Invalid input"
  /services/{serviceId}:
    get:
      summary: "Find service by ID"
      parameters:
      - name: "serviceId"
        in: "path"
        description: "ID of service to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Service"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Service not found"
definitions:
  Service:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      name:
        type: "string"
        example: "super_service"
      description:
        type: "string"
        default: ""
        example: "It is my super service description"
      createdAt:
        type: "integer"
        format: "int64"
        example: 1538741362